### ISSUE TITLE
Legal requirements when forking the IBM Plex fonts

### ISSUE THREAD

**Issue by twardoch** [IBM/type#100]
Hello, 

My understanding is that if one were to create derived versions of the IBM Plex fonts and distribute them, the following conditions must be fulfilled: 

1. The derived font **must** be distributed under [SIL Open Font License v1.1](https://github.com/IBM/type/blob/master/LICENSE.md). 
2. The derived fonts must retain the original fonts’ copyright notice (currently: `© 2017 IBM Corp. All rights reserved.`) but may add to it. (That’s just a consequence of the OFL). 
3. The derived font **must not** use the word `Plex` anywhere in the naming fields used for font selection because the original fonts’ license specifies `Plex` as the Reserved Font Name. 
4. The derived font **must not** use the word `IBM` anywhere in the naming fields used for font selection because `IBM` is a registered trademark of IBM Corp. 
5. The derived font **must not** use the phrase `IBM Plex` anywhere in the naming fields used for font selection because the original fonts specify `IBM Plex™ is a trademark of IBM Corp., registered in many jurisdictions worldwide.`
6. The derived font **must not** include the glyphs `uniEBE1`, `uniEBE3`, `uniEBE7`, `ibmlogo04` and `ibmlogo06`, as those all represent logos or symbols specific to IBM and may constitute visual trademarks. 

Am I right? I’m pretty sure on conditions 1-5 but I’m not sure on condition 6.

**Comment by BoldMonday** [comment]
I can't comment on the legal requirements, but am curious what files contain the glyphs `ibmlogo04` and `ibmlogo06`. Those glyphs are supposed to be named `uniEBE4` and `uniEBE6`.

**Comment by twardoch** [comment]
@BoldMonday 

```
./fonts/Serif/desktop/mac/IBMPlexSerif-Bold.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-ExtraLight.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-ExtraLightItalic.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-Italic.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-Light.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-LightItalic.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-Medium.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-MediumItalic.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-Regular.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-SemiBold.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-SemiBoldItalic.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-Text.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-TextItalic.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-Thin.otf
./fonts/Serif/desktop/mac/IBMPlexSerif-ThinItalic.otf
```

and the files for the same fonts in `./fonts/Serif/desktop/pc/`
