### ISSUE TITLE
Consider more distinguishable "el"

### ISSUE THREAD

**Issue by soviet-man** [IBM/type#101]
I don't like current "el" — stick that can be mixed up with one "1" or capital "i".
I believe "el" must be implemented like hockey or bandy stick 

For example,
![default](https://user-images.githubusercontent.com/33825590/33024931-868ec78a-ce1d-11e7-9ff9-082ce62f0dfb.png)

**Comment by jdw1996** [comment]
It seems like this is a duplicate of #66, so you may want to follow that issue if you're not already, as well.

**Comment by mjabbink** [comment]
v2 has new 1 which distinguishes itself more.
