### ISSUE TITLE
Remove attribute class CSS matching

### ISSUE THREAD

**Issue by diego-codes** [IBM/type#11]
Currently there are some css declarations that rely on attribute class selections:

![screen shot 2017-10-12 at 2 27 13 pm](https://user-images.githubusercontent.com/5973294/31515133-a92c9be2-af59-11e7-80e7-0038b020889e.png)

These types of classes are really problematic because it can create unintended restyling. For my case, I am using the classes that are all prefixed with `.ibm-type-checker`. This means that all of my classes are modified by the styles displayed above. This is definitely not intended and difficult to work with.

**Comment by seejamescode** [comment]
The max-width is no problem anymore and we talked about how the other odd use-case saves us a kilobyte or two. Let me know if you think there is a better way or want to keep the conversation going!
