### ISSUE TITLE
Consider better distinguishing design between zero and oh

### ISSUE THREAD

**Issue by akhepcat** [IBM/type#114]
in the spirit of issue 101,

O  and 0   should be distinguishable out-of-context.

i.e.,   1OO    should look like  one-oh-oh, always.

100  should look like one-zero-zero, always.

and it should be *obvious*  within the typeface, which is which.

overstriking the   zero  with a slash  is one method that clearly shows the difference - though due to the muddiness is not always the best action.   But something similar would be quite helpful, especially with regard to OCR.

**Comment by chengluyu** [comment]
The modification has been made in IBM Plex Mono - the '0' is design to have a dot inside the circle, because monospaced font is usually used in code display, which requires '0' and 'O' to be distinguishable. Do you want to do the same in Sans and Serif? I don't think it is a good idea.

**Comment by twardoch** [comment]
Adding a dotted zero in Sans and Serif could be done via an alternative glyph accessible through the "zero" OpenType feature.

**Comment by BoldMonday** [comment]
All IBM Plex sub-families (Mono, Sans and Serif) contain a normal zero, a dotted zero and a slashed zero.

In IBM Plex Mono dotted zero is the default form. In all other fonts normal zero is the default form.

All other variants of zeroes can be accessed either through the <zero> feature and/or through stylistic sets <ss03> and<ss04>.

**Comment by glebd** [comment]
I'm curious -- does anybody know which programming text editor or IDE supports the "zero" feature or choosing a particular stylistic set?

**Comment by akhepcat** [comment]
Thanks, @BoldMonday - that's useful and helpful to know, as it wasn't obvious upon initial checking.

**Comment by haktrik** [comment]
@glebd , @akhepcat  I'm also searching some straightforward way for making zero slashed. I can see this issue closed, can someone already find out the way for achieving such style for 0?
