### ISSUE TITLE
regular 'a' and italics 'a' different stories

### ISSUE THREAD

**Issue by lostmonster** [IBM/type#115]
Hello! 

It appears that the regular 'a' is two stories, and italics 'a' is one storey. Traditionally, fonts choose between one or two stories for a character, and the regular and italics follow that same pattern.

However, for Plex, that is not the case.  

What is the reasoning behind this?

Image regarding the above:
![ibmplex-regularvsitalics_3x](https://user-images.githubusercontent.com/18298999/33912348-5df6ac64-df4a-11e7-98ac-ce2b6fd09d51.png)

**Comment by twardoch** [comment]
> Traditionally, fonts choose between one or two stories for a character, and the regular and italics follow that same pattern.

Actually, IBM Plex follows the traditional model, in which roman "a" is double-storey and Italic "a" is single storey. The vast majority of fonts made between the 16th and 20th century followed that pattern.

Oblique fonts i.e. italic fonts that look like a slanted roman, only appeared about 100 years ago.

**Comment by lostmonster** [comment]
news to me! IBM Plex intended to employ 100+ year old type traditions for screens?

**Comment by twardoch** [comment]
I'm glad that I can provide some educational value :) Type generally is rooted in traditions, and the design of IBM Plex employs many techniques pioneered in newspaper type design at the beginning of the 20th century. 

Indeed, single-story italic "a"s are pretty much the only solution in serif typefaces, and in sanserif typefaces, they are probably about the half (the other half being obliques). If you look at the most popular sanserif fonts on MyFonts: 

http://www.myfonts.com/search/tag%3A%22sans+serif%22/fonts/?sort=sales

many of them have single-story italic "a"s while two-story roman"a"s: Brandon Grotesque, Proxima Nova, Gill Sans, Azo Sans, FF Kievit, FF Clan, Myriad Pro. Same goes for the most popular opensource sanserifs: Open Sans, Noto Sans, Lato, Alegreya Sans or Montserrat all follow the traditional italic model. 

Obliques are also a popular trend, e.g. in Helvetica, in Adrian Frutiger's designs (Univers, Frutiger, Avenir), or in Grotesk/Gothic sanserifs like Roboto, News Gothic, Franklin Gothic or Akzidenz Grotesk. But they're neither the traditional model nor in any way some majority.

**Comment by inferno986return** [comment]
IBM Plex Sans and Mono are humanist designs. Humanist typography is rooted in handwriting and serif typeface design. Most typefaces in the category use what is referred as true italics (which is great because I prefer that). I would say more, but @twardoch is has posted enough detail here.

Of course some humanist designs use oblique glyphs instead, it's upto the designer and what's best for the typeface overall. Furthermore, IBM Plex is a typeface superfamily and part of the design spec would be glyph consistency among the three typefaces.

**Comment by mjabbink** [comment]
@lostmonster  It’s equally a current model as it was 100+ years ago. You might check out Myriad Italic, Meta, Fira Sans, Akkurat, Greta, Irma, Fedra Sans, National (https://klim.co.nz/retail-fonts/national),Microsoft Segoe, FF Real, FF Kievit, FF Clan, FF Yoga, FF Unit, FF Info, FF Scala Sans, FF Milo, FF Dagny, Brown, DTL Argo, and Brandon. These are among the most popular typefaces across all mediums. Please take a look at all of them and I think you’ll gain a great understanding of why we made this decision.
