### ISSUE TITLE
Documentation: Alignment Examples Mixed Up

### ISSUE THREAD

**Issue by robertfackelman** [IBM/type#12]
On the documentation site, the "oops" examples of justified text and right aligned text have the incorrect descriptions next to the images. They should be swapped. See screenshot (screenshot is of Google Chrome on Mac).

![screen shot 2017-10-13 at 1 40 22 pm](https://user-images.githubusercontent.com/23707514/31559080-64ea3628-b01d-11e7-9452-5da96006761e.png)

**Comment by briandrum** [comment]
Except the first example isn't justified, it's centered.

**Comment by seejamescode** [comment]
Thanks!
