### ISSUE TITLE
Suggestion: capital Q

### ISSUE THREAD

**Issue by ghost** [IBM/type#120]
Thank you for the work you have done. I have faith that IBM Plex will be seriously improved.

As for the capital Q in all IBM Plex font types (serif, sans-serif and mono): may I suggest that the lower curve (which distinguishes it from the capital O) is extended upward beyond the lower part of the O-shape? Perhaps it is nice to have it go further to about ⅓ of the O-shape (the first ⅓). I am no typography specialist, by the way: it just seems to me that the change I suggest would make the Q look clearer and more aesthetically pleasing.

**Comment by mjabbink** [comment]
The aesthetics are in some regards up to personal taste. For us, the Q is gorgeous, functional, very legible, unique, conceptual, distinctive and uniquely IBM.
