### ISSUE TITLE
Suggestion: ≔ and ≝

### ISSUE THREAD

**Issue by ghost** [IBM/type#122]
I am no great typographer, but would it not be nice if the ≔ and ≝ are made much clearer? In fact, it would be nice if the =, ≔, ≠, ≡ and ≝ and the like are more looking like each other (at least in size or general appearance), yet still sufficiently different for recognition.

**Comment by mjabbink** [comment]
we do not have ≔ and ≝ in the current design. We will design a version of Plex with full mathematical glyphs next year.

**Comment by inferno986return** [comment]
So that's full support for the Mathematical Operators block in 2019?
I just want to make sure I get it right for the Wikipedia article I'm working on.
https://en.wikipedia.org/wiki/IBM_Plex

**Comment by seejamescode** [comment]
Off-topic: @inferno986return, thanks for working on that article! One clarification I would like to make is that the Apache license is only for the web development code attached. There will soon be a separation of repos that will help with that confusion.

**Comment by inferno986return** [comment]
Sure, sure. I should probably create a separate issue for the Wikipedia article.
