### ISSUE TITLE
family usWeightClass values

### ISSUE THREAD

**Issue by m4rc1e** [IBM/type#13]
The Thin weights are set to 100. This can create issues in some applications

>Having a weightclass of 100 or 200 can result in a "smear bold" or (unintentionally) returning the style-linked bold. Because of this, you may wish to manually override the weightclass setting for all "extra light," "ultra light" or "thin" fonts.

 https://www.adobe.com/devnet/opentype/afdko/topic_font_wt_win.html

I recommend you change Thin to 250 and ExtraLight to 275

**Comment by seejamescode** [comment]
Sharing with the Plex crew now, thanks!

**Comment by twardoch** [comment]
@m4rc1e I was only aware of this problem to affect CFF-flavored OpenType fonts (`.otf`). Can you confirm that the problem of `OS/2.usWeightClass < 250` also affects TTF-flavored `.ttf` OpenType fonts?

**Comment by seejamescode** [comment]
@BoldMonday, thoughts?

**Comment by m4rc1e** [comment]
At GF, we have a check to ensure that each style is matched to a particular usWeightClass value.

https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/googlefonts.py#L597-L611

A lot of users still use old Browsers (Internet cafes etc) so we still care about Win7. This thread is rather insightful into the issue:

http://www.typophile.com/node/84518


Here's some interesting comments:

> I hate to say it, but since AFAIK many GDI apps even on Windows 7 are still broken in handling usWeightClass, it seems to me that sane font vendors are not likely to use usWeightClass values less than 250. It's not only Adobe who does such odd things in this regard.

-T Phinney 


> And if, following that standard, you set the usWeightClass value of any of your fonts as 100 or 200, they may end up displaying as heavier than a font with a value of 300 in GDI.

-J Hudson

Ok, I haven't personally tested these assumptions and @twardoch may be right about this not being relevant to ttf. However, for consistency purposes, I'd prefer these values conform to our linter. 

I'm totally open for any reasons against doing this.

**Comment by BoldMonday** [comment]
We'd rather stick to standards and not use hacks to circumvent any legacy issues. Anything we can do to avoid post-processing on generated binaries in our production workflow is welcome here.

And as @twardoch rightfully mentioned: this legacy issue where fonts with weight values < 250 are rendered as faux bold applies to CFF fonts only.

**Comment by davelab6** [comment]
Thanks for the feedback, we'll test this directly to be sure :)
