### ISSUE TITLE
Unable to open Sketch file…

### ISSUE THREAD

**Issue by briandrum** [IBM/type#2]
…in either version 46.2 ((44496) or beta version 47 (45392)

<img width="532" alt="screen shot 2017-10-05 at 10 28 11 am" src="https://user-images.githubusercontent.com/114522/31232502-098f22f4-a9b8-11e7-833b-1d271476b5e0.png">

**Comment by seejamescode** [comment]
Thanks for the find! Give the download link a shot now.
