### ISSUE TITLE
Design—not on the Grid?

### ISSUE THREAD

**Issue by qqpin** [IBM/type#25]
I think type in on the grid, but the container for buttons are not?
Same for the side nav.

<img width="902" alt="screen shot 2017-10-20 at 2 54 54 pm" src="https://user-images.githubusercontent.com/14185008/31837404-b0947906-b5a6-11e7-90c9-7de51397461e.png">
<img width="239" alt="screen shot 2017-10-20 at 2 56 19 pm" src="https://user-images.githubusercontent.com/14185008/31837473-e526e6ae-b5a6-11e7-8add-79c0e3c46e5e.png">

**Comment by seejamescode** [comment]
Which browser and which version of IBM Grid Checker are you using?

**Comment by qqpin** [comment]
Chrome, Version 61.0.3163.100
IBM Grid Checker 1.0.0

**Comment by seejamescode** [comment]
![screen shot 2017-10-23 at 11 28 33 am](https://user-images.githubusercontent.com/7519029/31900825-55142194-b7e5-11e7-9c33-9799300379ae.png)

Mine is perfect. I wonder if there is another Chrome extension messing with your’s.

**Comment by seejamescode** [comment]
@qqpin, can you send a screenshot of the whole window?

**Comment by qqpin** [comment]
![screen shot 2017-10-25 at 10 40 42 am](https://user-images.githubusercontent.com/14185008/32004930-ff8aa17a-b970-11e7-8a7b-e483d1f4c490.png)

**Comment by seejamescode** [comment]
Whatever that was seems to be resolved now!
