### ISSUE TITLE
Design—graphic 

### ISSUE THREAD

**Issue by qqpin** [IBM/type#27]
Use type H instead of Type I

<img width="851" alt="screen shot 2017-10-20 at 2 59 23 pm" src="https://user-images.githubusercontent.com/14185008/31837569-50fa5564-b5a7-11e7-995b-8d97530662f4.png">

**Comment by seejamescode** [comment]
But H is for product experiences. Is there an adjustment you want to make to the editorial type set?

**Comment by qqpin** [comment]
I think I only want this image the same scale as other images. it looks bigger than others.
<img width="571" alt="screen shot 2017-10-23 at 12 19 35 pm" src="https://user-images.githubusercontent.com/14185008/31900470-78bd2512-b7ec-11e7-990f-2c026e711609.png">
<img width="571" alt="screen shot 2017-10-23 at 12 19 30 pm" src="https://user-images.githubusercontent.com/14185008/31900471-78c7ec54-b7ec-11e7-930d-35f8c627a411.png">
