### ISSUE TITLE
Design—little things

### ISSUE THREAD

**Issue by qqpin** [IBM/type#29]
- [x] Just call it "Weights" instead of "Suggested default weights" 
<img width="388" alt="screen shot 2017-10-20 at 3 03 14 pm" src="https://user-images.githubusercontent.com/14185008/31837718-d76db7f8-b5a7-11e7-8ee8-e2a133d65efa.png">

- [x] Make the purple 1 unit, not 2 units
<img width="950" alt="screen shot 2017-10-20 at 3 06 44 pm" src="https://user-images.githubusercontent.com/14185008/31837850-53533f78-b5a8-11e7-9750-c460a0cebd43.png">

- [ ] Spacing here need to be adjusted. 
<img width="771" alt="screen shot 2017-10-20 at 3 16 07 pm" src="https://user-images.githubusercontent.com/14185008/31838313-40c391f8-b5aa-11e7-94d7-0b63f0528380.png">
Let's do: line + 1 unit + text + 3 unit gap to the next. Blue color for code snippet.  
<img width="988" alt="screen shot 2017-10-20 at 3 20 08 pm" src="https://user-images.githubusercontent.com/14185008/31838311-3b3a0262-b5aa-11e7-8f3c-f06d4c8fc1f6.png">

- [ ] Need a max-width here
<img width="415" alt="screen shot 2017-10-20 at 3 26 10 pm" src="https://user-images.githubusercontent.com/14185008/31838496-1234dea4-b5ab-11e7-87f7-802ba2e3ae1e.png">

- [ ] For this:
<img width="771" alt="screen shot 2017-10-20 at 3 27 21 pm" src="https://user-images.githubusercontent.com/14185008/31838533-3f588a7a-b5ab-11e7-8b16-15fe1523ba0b.png">

The line should layout like this way. Warning should be in red color.
<img width="592" alt="screen shot 2017-10-20 at 3 27 39 pm" src="https://user-images.githubusercontent.com/14185008/31838540-454eebe0-b5ab-11e7-8e7c-9c514568e61d.png">

- [ ] Make 7 units to 3 units
<img width="887" alt="screen shot 2017-10-20 at 3 29 39 pm" src="https://user-images.githubusercontent.com/14185008/31838606-8cc7a6a6-b5ab-11e7-9c57-9a8f2036ed83.png">

- [x] Missing the top divide line 
<img width="789" alt="screen shot 2017-10-20 at 3 30 48 pm" src="https://user-images.githubusercontent.com/14185008/31838638-b10467b6-b5ab-11e7-8688-bfd33794e49f.png">

**Comment by seejamescode** [comment]
> Use #757575 for these title

#757575 is inaccessible on #F3F3F3

**Comment by qqpin** [comment]
:fearful:
