### ISSUE TITLE
Design—little things 2

### ISSUE THREAD

**Issue by qqpin** [IBM/type#30]
- [x]  This is duplicated. I think the bottom one is the right content.

<img width="243" alt="screen shot 2017-10-20 at 3 32 04 pm" src="https://user-images.githubusercontent.com/14185008/31838678-ec874858-b5ab-11e7-8a63-04a4b4a2f11a.png">

- [ ] Need to re rag this type.
<img width="778" alt="screen shot 2017-10-20 at 3 34 15 pm" src="https://user-images.githubusercontent.com/14185008/31838742-2afe423a-b5ac-11e7-9826-e2d08ee8842b.png">

**Comment by seejamescode** [comment]
What do you want for the rerag?

**Comment by qqpin** [comment]
<img width="489" alt="screen shot 2017-10-24 at 5 37 05 pm" src="https://user-images.githubusercontent.com/14185008/31969265-fe2ffc24-b8e1-11e7-9b86-4ff597361d12.png">
