### ISSUE TITLE
Design—toggle

### ISSUE THREAD

**Issue by qqpin** [IBM/type#32]
We need to have those toggles to show different type sets and breakpoints.

<img width="537" alt="screen shot 2017-10-20 at 3 50 33 pm" src="https://user-images.githubusercontent.com/14185008/31839299-79f79902-b5ae-11e7-8b92-fb2a5a4da852.png">

**Comment by seejamescode** [comment]
You did not provide what these toggles do for the margin bottom values.

**Comment by seejamescode** [comment]
Bump

**Comment by qqpin** [comment]
https://ibm.box.com/s/lc28bipsc043mk7ot6rlsvek33ltaihj
