### ISSUE TITLE
Open Slack client instead of Slack in the browser

### ISSUE THREAD

**Issue by teardroponfire** [IBM/type#38]
**Current behavior**: When clicking on the Slack channel link in the footer, the Slack channel is opened in the same browser window.

**Desired behavior**: When clicking on the Slack channel link in the footer, the Slack channel is opened in the Slack client. Alternatively, open the channel in a new window.

**Comment by BrandonDH** [comment]
Hi @teardroponfire, I came across this issue during Hacktoberfest - https://hacktoberfest.digitalocean.com/ and just opened a pull request here with what I think are steps towards a possible fix - https://github.com/IBM/type/pull/58. If this isn't meant to be open to the public just let me know! 

-Brandon
