### ISSUE TITLE
Make line length optional

### ISSUE THREAD

**Issue by teardroponfire** [IBM/type#39]
**Current behavior**: The `max-width` property is automatically assigned using IBM type. This is causing content blocks that span the width of the page to wrap which is undesired.

![image](https://user-images.githubusercontent.com/1015199/31957924-da1f8d58-b8b5-11e7-85bf-2047bdc9a314.png)

**Desired behavior**: Make the line length enforcement optional. Guidance is appreciated, but ultimately should be up to the designer/developer to apply.

**Comment by seejamescode** [comment]
Hey Kev, this is going to be default behavior to counter designers and developers not considering line length. Please apply your desired line length on top of it if preferred.
