### ISSUE TITLE
Don't apply bottom margin to list item elements

### ISSUE THREAD

**Issue by teardroponfire** [IBM/type#40]
**Current behavior**: Bottom margin is applied to all elements, including list items, resulting in undesired styling.

![image](https://user-images.githubusercontent.com/1015199/31958385-2caf46fc-b8b7-11e7-8680-1d8e4c0e2d09.png)

**Desired behavior**: Bottom margin is not applied to list item elements. Designer/developer can add bottom margin as desired.

**Comment by seejamescode** [comment]
Does this happen when you add the type style to the `ul` instead of individual `li`s?

**Comment by seejamescode** [comment]
Confirmed that they type style should be applied to the `ul` and not `li`: https://codepen.io/seejamescode/pen/KyGaxx
