### ISSUE TITLE
Design—lg

### ISSUE THREAD

**Issue by qqpin** [IBM/type#43]
- [ ] Make all the spacing between section 6 units in lg.
<img width="713" alt="screen shot 2017-10-25 at 10 10 41 am" src="https://user-images.githubusercontent.com/14185008/32003374-cfe5467c-b96c-11e7-8345-f77f268ca652.png">

- [ ] Make all blue to #0F6DFF, including icons.
<img width="796" alt="screen shot 2017-10-25 at 10 14 14 am" src="https://user-images.githubusercontent.com/14185008/32003506-49f3457c-b96d-11e7-914d-2a675103bc75.png">

- [ ] Seems this image hasn't swapped. It looks blury.
<img width="1006" alt="screen shot 2017-10-25 at 10 16 00 am" src="https://user-images.githubusercontent.com/14185008/32003590-89bae408-b96d-11e7-8220-d003e52dc93f.png">

**Comment by seejamescode** [comment]
Images were swapped already.

**Comment by qqpin** [comment]
not this one: https://ibm.box.com/s/dqegekcle0mll8c48vgtn51ng9y22uf6
