### ISSUE TITLE
Design—New video added

### ISSUE THREAD

**Issue by qqpin** [IBM/type#44]
Line-length:
https://ibm.box.com/s/gfxg93mysrap2iposxvrh8xs88ftshct

Tracking:
https://ibm.box.com/s/gf6for7nzmfnx0y0fnexnkscdxq8v1bj

**Comment by qqpin** [comment]
Is it possible to have all video play automatically and loop?

**Comment by davelab6** [comment]
> Is it possible to have all video play automatically and loop?

Yes, using the HTML5 `<video>` tag attributes `autoplay` and `loop` like this


```
<video autoplay loop>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
  Your browser does not support the video tag.
</video>
```

**Comment by seejamescode** [comment]
The reason the accessibility team wanted us to switch from gifs to video is to stop looping.
