### ISSUE TITLE
What is IBM Type?

### ISSUE THREAD

**Issue by neilpanchal** [IBM/type#59]
Reading the introduction is vague and completely baffling.

What is IBM Type? Explain it in one sentence. The current explanation, quote:

> Typography is the appearance and arrangement of type. Each word or paragraph lives in a grid system—creating helpful alignments, harmonious relationships and clear organizations. Typography should reflect careful choices in size, placement, and weight to create useful hierarchies to guide users through the content.
> 
> With our new bespoke corporate typeface, IBM Plex™, comes a new set of guidance and best practices. IBM typography is international and modern to reflect our brand and our design principles.

The visitor has still no clue if IBM Type is a new font (IBM Plex is?) or a new paradigm or what the heck is it? Is it a guideline for typography at IBM? Set of general principles? New CSS framework?

Of course this is my personal opinion, but chimes with the top comment on HN:
https://news.ycombinator.com/item?id=15653897

It'd be nice to have some clarification. I love the IBM Plex font, especially monospaced.

Also, it would be good to have the licensing information on the page.

**Comment by seejamescode** [comment]
Thanks for the attention to detail, @neilpanchal.

Our current repo for IBM Type is:

> The package of IBM’s new typeface, IBM Plex, and accompanying typography code.

I will keep this in mind when we ship the new guidelines page.
