### ISSUE TITLE
Does it support Cyrillic? 

### ISSUE THREAD

**Issue by zemtsov** [IBM/type#60]
Looks like IBM fonts doesn't support Cyrillic. How can it be used in presentations by IBMers from Russia?

<img width="828" alt="screen shot 2017-11-09 at 10 46 51" src="https://user-images.githubusercontent.com/7241276/32594061-860fb8f4-c53b-11e7-8477-f821932f5fcc.png">

**Comment by seejamescode** [comment]
Cyrillic is still in the works! In the meantime, we recommend the following [fallbacks.](https://github.com/IBM/type/blob/master/css/ibm-type.css#L810-L824)
