### ISSUE TITLE
Tops of glyphs need some pixel hinting

### ISSUE THREAD

**Issue by idontusenumbers** [IBM/type#61]
Would be nice to have clean and consistent vertical lines too, L in 'Plex' and 'should' looks different, also is 2 pixels wide but not aligned to pixels so there's a slight haze in 'should' and a terrible blur on 'Plex'

MacOS 10.12.6; Chrome
![image](https://user-images.githubusercontent.com/1175031/32626942-6e303414-c556-11e7-8e8f-37278bc20404.png)

**Comment by seejamescode** [comment]
@BoldMonday, thoughts?

**Comment by BoldMonday** [comment]
Chrome on Mac does not use the hinting information we put into the fonts unfortunately. It has its own intelligence for rasterizing type which clearly favours a sharp rendering of the baseline yet seems to struggle with the other vertical dimensions of the type.

**Comment by seejamescode** [comment]
Thanks for the insight, @BoldMonday!
