### ISSUE TITLE
Plex is a fairly attractive font, but...

### ISSUE THREAD

**Issue by keshlam** [IBM/type#62]
... Not everyone is working in Javascript. 

I want to install it for use in desktop applications and presentations... and specifically, I want to install it for use on my Linux box to create Open Office/Libre Office presentations.

I've probably missed something obvious, but I don't see instructions for adding this font to those available to Linux apps which are not written in javascript.

Is this broader use really not yet supported? Or just not documented?

**Comment by joestrouth1** [comment]
Have you checked `/fonts`? It contains your usual `.otf`/`.ttf` files and other formats too.

**Comment by seejamescode** [comment]
@joestrouth1 is correct. All file types are in `./fonts`. Hope that gets you rolling with what you wanted!
