### ISSUE TITLE
Tagged release versions on GitHub

### ISSUE THREAD

**Issue by alanorth** [IBM/type#70]
Thanks for open sourcing this great font family. I hope that we will eventually be able to install this through system package managers like Homebrew on macOS. One requirement for inclusion in that particular package manager's repository is that _package releases must be tagged_, so this is just a heads up and a friendly request for you to start tagging your releases. Thanks!

See the formula cookbook where it states this requirement: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by samwrigley-dewsign** [comment]
I agree with @alanorth, it would be great to be able to install the fonts in a way that meant they could be easily updated. As this is still in development and not a stable release yet, I'm assuming a number of tweaks could be made to the typeface, especially considering it's being open sourced.

Perhaps there is a way to allow installing via [Skyfonts](https://skyfonts.com/)? It would ensure users had the latest version should any changes be made.

Can't wait to use IBM Plex in a project!

**Comment by samwrigley** [comment]
I agree with @alanorth, it would be great to be able to install the fonts in a way that meant they could be easily updated. As this is still in development and not a stable release yet, I'm assuming a number of tweaks could be made to the typeface, especially considering it's being open sourced.

Perhaps there is a way to allow installing via Skyfonts? It would ensure users had the latest version should any changes be made.

Can't wait to use IBM Plex in a project!

**Comment by davelab6** [comment]
Skyfonts will happen when the fonts are onboarded into Google Fonts (soon)

**Comment by seejamescode** [comment]
FRIDAY NIGHT GITHUB RELEASE PARTY
No cover / All ages / Free IBM Plex
https://github.com/IBM/type/releases/

**Comment by alanorth** [comment]
Thank you, @seejamescode. I've submitted IBM Plex to Homebrew's font cask repository. Issue to watch: https://github.com/caskroom/homebrew-fonts/pull/1365.
