### ISSUE TITLE
The "r" in Plex Mono

### ISSUE THREAD

**Issue by bartsnapp** [IBM/type#71]
The "r" in Plex Mono is a bit strange (at least to my eye, and on my machine). 

The left serif is too large, and makes it look more like a tiny serif I 
![ibmplex-r](https://user-images.githubusercontent.com/1376703/32665191-7b718fb4-c601-11e7-9e54-d8e670b9763b.png)

**Comment by seejamescode** [comment]
@mjabbink and @BoldMonday, thoughts?

**Comment by mjabbink** [comment]
We’re investigating further but in context of it in a word or set of words it reads.

**Comment by mjabbink** [comment]
![screen shot 2017-11-10 at 1 21 33 pm](https://user-images.githubusercontent.com/32881239/32672727-2bb691ea-c61a-11e7-908f-e45eb22ff01f.png)

**Comment by mjabbink** [comment]
also, those light weights are NOT to be used at those sizes. It’s not legible and not designed for that at all. Of course it will not read.

**Comment by bartsnapp** [comment]
Understood. Thanks for checking into it, and thanks for a new exciting font!

**Comment by mjabbink** [comment]
<img width="258" alt="screen shot 2017-11-10 at 1 24 43 pm" src="https://user-images.githubusercontent.com/32881239/32672819-9340bcaa-c61a-11e7-966e-bf453befd63d.png">

**Comment by mjabbink** [comment]
We may change the design and we’re also looking into the italic a in Mono.

**Comment by seejamescode** [comment]
Thanks for the issue, @bartsnapp and for the response, @mjabbink. It is now on the Plex team’s radar!
