### ISSUE TITLE
Plex Mono Thin is very thin...

### ISSUE THREAD

**Issue by bartsnapp** [IBM/type#72]
Plex Mono Thin is too thin to be used on screen. I really the overall look of the thin version of  Plex Mono, but it is currently unusable. 
![thin](https://user-images.githubusercontent.com/1376703/32665393-0e74ffd0-c602-11e7-8e0e-2818b1f6c149.png)

**Comment by seejamescode** [comment]
Hey @bartsnapp, thanks for the issue! Our design guidelines will be back up next week. In them, we only recommend Light, Regular, and SemiBold for digital experiences. The others’ are more meant for print.
