### ISSUE TITLE
whenver possible...

### ISSUE THREAD

**Issue by hg-lr** [IBM/type#73]
![image](https://user-images.githubusercontent.com/2271066/32674266-d6cf11aa-c652-11e7-8e2d-b442aed0cdb3.png)
![image](https://user-images.githubusercontent.com/2271066/32674292-edf9e026-c652-11e7-93c6-3e1e6971a950.png)

also why an img element?

**Comment by seejamescode** [comment]
Hi @hg-lr! Are you asking why we recommend for IBMers to replace Helvetica Neue or are you pointing out a typo?

And I agree that the image should not exist on the brand center. However, that website is a temporary destination for IBMers as we tweak the design guidelines.

**Comment by hg-lr** [comment]
lel no ... it's just, the font used in the "IBM Brand Center" image is Helvetica...

**Comment by hg-lr** [comment]
besides that, i do like the plex font family itself. very much so.

**Comment by seejamescode** [comment]
Oh, lol

That team will migrate soon. Thanks for the heads up.
