### ISSUE TITLE
[Suggestion] Adding I and 1 as sans serif opentype alternative glyph in IBM Plex Sans

### ISSUE THREAD

**Issue by heyheni** [IBM/type#74]
Great Font! You did an awesome job crafting it. I understand it's a corporate font for IBM and there it does make sense that the uppercase i and 1 looks like the I in the IBM logo. But if you, as you're saying in the introduction Video, want that everyone should using your Font, please add a sans serif variety of 1 and the uppercase I in IBM Plex Sans. Since the lowercase i has no serifs.

**Comment by seejamescode** [comment]
Glad you are enjoying Plex and thanks for the issue! This is a duplicate of #66, so we are tracking the issue there.
