### ISSUE TITLE
Using IBM Plex in a presentation

### ISSUE THREAD

**Issue by ajstarks** [IBM/type#76]
See: https://github.com/ajstarks/dotgo-otherside/blob/master/dotgo-ibm.pdf

for example of using IBM Plex in an existing presentation.  The presentation was done with the [pdfdeck  ](https://github.com/ajstarks/deck/tree/master/cmd/pdfdeck)command, using this command line:

`pdfdeck -pagesize 1920,1080 -sans IBMPlexSans-Regular -serif IBMPlexSerif-Regular -mono IBMPLexMono-Regular dotgo.xml`

The pdfdeck command used the TTF files from the distribution.

I note that the Regular weight may be bit too light, compared to the original version which used Fira Sans and Charter.  The IBM Plex Medium may be a better choice for presentations.

**Comment by seejamescode** [comment]
Thanks for the example @ajstarks! We hope medium fits your needs more. Check back later this week for the return of the typography guidelines.

**Comment by ajstarks** [comment]
Many thanks for making IBM Plex available.  (I've attached a Medium version for comparison)
Looking forward to the guidelines.  I'm interested in your view of using Plex in presentations.

[dotgo-ibm-med.pdf](https://github.com/IBM/type/files/1465125/dotgo-ibm-med.pdf)

**Comment by nickleeh** [comment]
IBM Plex Mono is beautiful. I also find that the "Reguar" is too thin compared to other fonts, such as Menlo, Fira Code, even SF Mono. But "Medium" is too dark. Is it possible to have a not too thin (too light), not too dark font?
