### ISSUE TITLE
Add ligatures

### ISSUE THREAD

**Issue by ctwise** [IBM/type#77]
There don't appear to be any ligatures in the mono font. Please add them.

**Comment by davelab6** [comment]
Which character pairs do you propose be ligated? :)

**Comment by glebd** [comment]
This looks like a duplicate of #63

**Comment by seejamescode** [comment]
Hi @ctwise, thanks for the ask!

Like @glebd mentioned, this is a duplicate of #63. Please continue the conversation there if you have some recommendations.
