### ISSUE TITLE
54MB zip file for a font?

### ISSUE THREAD

**Issue by sterlingcrispin** [IBM/type#78]
The download link at https://ibm.github.io/type/ is for the entire repo including 34MB of brand guidelines which includes a second copy of all of the fonts.

The docs folder also includes a third copy of all of the fonts.

Really I just wanted one copy and nothing else, the fonts and nothing else should be made available as a release and linked at https://ibm.github.io/type/

**Comment by seejamescode** [comment]
Hey @sterlingcrispin, I understand the pain. The download link for the repo was a quick fix for this. We will add a more specific zip soon.

Best,
James

**Comment by seejamescode** [comment]
Resolved: https://raw.githubusercontent.com/ibm/type/master/ibm-plex.zip

**Comment by davelab6** [comment]
Why not place that zip in the release page? It doesn't really belong in the
git repo
