### ISSUE TITLE
Scandinavian characters missing

### ISSUE THREAD

**Issue by trondhuso** [IBM/type#79]
Checked out the font at font squirrel and looks amazing. One thing though: In that version no Scandinavian characters was available. 
Expected to find characters æ, ø and å.

**Comment by seejamescode** [comment]
Hey @BoldMonday, can you confirm whether or not our files support these glyphs yet?

**Comment by BoldMonday** [comment]
Those glyphs are part of the fonts: check the tab "Glyphs" at https://www.fontsquirrel.com/fonts/ibm-plex.

The font tester at Fontsquirrel is broken and does not seem to render *any* accented letter for *any* font.

**Comment by seejamescode** [comment]
Thanks Paul!
