### ISSUE TITLE
Declaring the font-family requires escaped quotes

### ISSUE THREAD

**Issue by marijohannessen** [IBM/type#8]
When declaring IBM Plex Sans as a font-family, it only works when I declare it with the escaped quotes:

```
font-family: "\"ibm-plex-sans\"";
```

This makes the font show up in the inspector with the escaped quotes.

Ideally, to keep it clean, I would like to be able to declare it like this:

```
font-family: "ibm-plex-sans";
```

**Comment by seejamescode** [comment]
Thanks!
