### ISSUE TITLE
Greek, math and others

### ISSUE THREAD

**Issue by m3adi3c** [IBM/type#80]
First off, thank you so much for open sourcing this and putting so much effort in the whole family! I have Plex-ed all apps that I use (Alfred, iTerm, Emacs, Firefox, Mail) and I'm really loving it!

One question, though: do you plan on expanding all the families to most, if not all languages? In my case, as a mathematician and using Emacs Org mode for some notes, I like the "prettification" that it offers, displaying LaTeX entities as UTF8 characters. This way I noticed that Greek letters are missing. (I also noticed Scandinavian and Cyrillic mentioned as lacking.)

Emacs finds some fallback, but I would like them natively.

I assume that, since it's such a large project, *all families* will, eventually, include support for most languages and math symbols. Am I right in assuming and hoping for this? 😄 

Once again, thank you so much for the effort!

**Comment by mjabbink** [comment]
Early 2018 will kick-off Arabic, Greek, Hebrew, Hindi and Thai. CJK will kick off middle of 2018. Extended Math symbols will come in 2019.

**Comment by m3adi3c** [comment]
Great to hear this, thank you very much! It's reassuring to have confirmed the ample intentions that I was hoping for in developing this font!

Keep up the great work, thank you for your time and effort you put into this!
