### ISSUE TITLE
README's Developer Tutorial walkthrough link is broken

### ISSUE THREAD

**Issue by viniciushaga** [IBM/type#82]
In the Developer Tutorial section the link "**this walkthrough**" containing the url https://ibm.github.io/type/code.html is broken, responding with a 404 error.

**Comment by seejamescode** [comment]
Thanks for the issue, @viniciushaga! Check #81 for updates.

**Comment by viniciushaga** [comment]
Oh, my bad, I didn't see #81 before. Thanks @seejamescode .
