### ISSUE TITLE
'r' in Plex Mono

### ISSUE THREAD

**Issue by hernan3009** [IBM/type#85]
I was trying Plex Mono for codding.  Overall, I really like it, but I found the 'r' glyph distracting, especially (but not only) when it is located next to a "t", "f" or "P". I bet that it is related to its up left corner part. Also, when it is isolated and its meaning is not evident by context (e.g. in 'nu_r') my brain needs to think twice in order to recognize it as an r. The effect is slightly more pronounced when watching far from the screen.

I am not typographer so my thoughts my be incorrect.

Regards

Hernán

**Comment by glebd** [comment]
Oh my, I like the 'r' very much.

**Comment by mjabbink** [comment]
The "r" in Plex Mono has been refined and works significantly better. It should resolve any legibility issue and retain it’s original design integrity.
