### ISSUE TITLE
Cyrillic and other non-latin charset support

### ISSUE THREAD

**Issue by NiKoTron** [IBM/type#87]
Awesome font! but I think that it would be better if it supported not only the latin based charsets. do you have a plan for this?

**Comment by BoldMonday** [comment]
Yes, more languages and scripts will be added in 2018. Cyrillic is in the final stages of development as we speak. :)

**Comment by mjabbink** [comment]
Early 2018 will kick-off Arabic, Greek, Hebrew, Hindi and Thai. CJK will kick off middle of 2018.

**Comment by vkamelin** [comment]
Cyrillic in 2017!!!

**Comment by mjabbink** [comment]
We will have in 2017 but given the holiday season it’s likely to be early 2018. Cyrillic will be in Sans, Serif and Mono!

**Comment by mjabbink** [comment]
@NiKoTron @vkamelin Cyrillic is now complete! It will be posted in the next week or two. We have Sans, Mono and Serif versions of Cyrillic.

**Comment by nikolaeu** [comment]
Can't wait for cyrillic @mjabbink!

**Comment by sergekir** [comment]
@nikolaeu it's here:
https://github.com/IBM/type/pull/130

**Comment by jbarco** [comment]
Is there any estimated release date for Arabic, Greek, Hebrew, Hindi and Thai?
