### ISSUE TITLE
Consider a slashed zero in IBM Plex Mono

### ISSUE THREAD

**Issue by glebd** [IBM/type#89]
The dotted zero renders off-centre at certain point sizes on Windows + ClearType and looks a bit ugly when that happens. I think an off-centre *slashed* zero would still look OK.

**Comment by BoldMonday** [comment]
All IBM Plex fonts contain a slashed zero which can be accessed either through the <zero> feature or one of the stylistic sets.

**Comment by glebd** [comment]
The problem is that dotted zero is the default and none of the editors or IDEs I use allow me to choose a particular stylistic set. Can you explain what the “zero” feature is?

**Comment by BoldMonday** [comment]
It is an OpenType feature:
https://www.microsoft.com/typography/otspec/features_uz.htm
