### ISSUE TITLE
Baseline Grid for vertical rhythym

### ISSUE THREAD

**Issue by vilav** [IBM/type#9]
Hello

Been waiting for this font, so stocked it's here after seeing it on twitter!
Are there values to use the typeface at different sizes such that a vertical rhythm is maintainted. 

EX: Using it in a Keynote deck at 18 _pts_ on a _1440x900 px_  canvas. What's the right value for line-spcing that will ensure a even vertical rhythm?

**Comment by seejamescode** [comment]
Hey @qqpin, do we have any guidance for presentations yet?

**Comment by qqpin** [comment]
Hi
What are you looking for? Keynote presentation guidance? or line-height breakdown for selected type scales? We don't have guidance for presentation for now. but in general, we use 26px leading (line-height) for 18px.

**Comment by vilav** [comment]
Hi @qqpin, hoping to get some guidance on setting up a baseline grid and having some corresponding font sizes to make it more visually pleasing and easier to read.

For instance: https://codepen.io/toddpadwick/full/KzLBrW

This is in pixels. Keynote sets fonts in points (as far as I can tell). Looking to see if there's a way to setup the baseline grid and font size in a manner similar to the link above where all text lines up to the grid well.

**Comment by seejamescode** [comment]
Thanks for more context @vilav.

When reading [this article,](https://www.smashingmagazine.com/2012/12/css-baseline-the-good-the-bad-and-the-ugly/) I notice the difference between following a baseline and our implementation. A baseline grid sets all line-heights at a multiple of the smallest line height (which would be 16px in our case).

When you look at our [scale,](https://github.com/IBM/type/blob/master/src/styles/_variables.scss#L17-L109) you will notice that our line heights are much more detailed to what we find most optically pleasing. We do not plan on supporting a scale that focuses on a baseline grid. Thank you for bringing this to our attention!
