### ISSUE TITLE
Consider slightly less curvy braces in IBM Plex Mono

### ISSUE THREAD

**Issue by glebd** [IBM/type#91]
It's a matter of taste but I prefer slightly less curvy (or even non-curvy) braces (`{}`).

**Comment by mjabbink** [comment]
See that. Have heard from another friend. Good to know and will keep the issue on the burner.

**Comment by bartsnapp** [comment]
As a counter point, the current curly braces are quite distinct from both parentheses and square brackets... This is a good thing.

**Comment by mjabbink** [comment]
I like them as well. They do stand out clearly for me.

**Comment by BoldMonday** [comment]
The curvy braces are on purpose very curvy in order to be clearly different from brackets and parentheses. It was a functional decision.

**Comment by NiklasBr** [comment]
The curvy braces look great and unique on high DPI screens (e.g. "retina" screens) but they do look a bit blurry on my Dell U2415.
