### ISSUE TITLE
No text figures

### ISSUE THREAD

**Issue by octoploid** [IBM/type#92]
Are there plans to add text figures to the fonts?

**Comment by mjabbink** [comment]
Not anytime soon. We purposely choose NOT to include them. Trying to be essential. One does not need them to good typography and we like the honesty of the aligning figures,

**Comment by twardoch** [comment]
I personally don't like the really small-size text figures ("old-style") but I think Matthew did a superb job on the Georgia “universal” numerals — with just subtle ascending/descending elements and a solid size. But I can't say if I desire text figures for Plex.

**Comment by dlewand691** [comment]
I would prefer to have old-style numerals. When used in body copy, they flow nicer than standard tabular/lining numbers which seem abrupt and disrupt the reading flow. It's also good typographic practice to have both, but use them appropriately. 

Also, proportional numerals would be a good addition as well. 

Some great reference and examples here: https://practicaltypography.com/alternate-figures.html

**Comment by mjabbink** [comment]
Not really. That is what people think is good practice but it’s not true. Think about Helvetica, Univers, Frutiger, Gill Sans, Syntax, akzidenz Grotesk, Franklin Gothic, Trade Gothic, etc. By your statement these would all fall short for implementing good typography. 
 —
 Mike Abbink
 
 Executive Creative Director,
 Brand Experience and Design
 
 +1 917 291 7516 mobile
 mjabbink@us.ibm.com
 
 
 —
 Sent from my iPhone 
 using IBM Verse
 
 On Nov 21, 2017, 4:59:08 PM, notifications@github.com wrote:

**Comment by dlewand691** [comment]
True those fonts don't have old-style numerals but that doesn't mean they're typographically wrong. I would disagree and say that it is true and it is good typographic practice for readability, especially in body copy.
