### ISSUE TITLE
Support for local() for non-regular weights

### ISSUE THREAD

**Issue by seejamescode** [IBM/type#94]
We released pre-release [v0.5.0](https://github.com/IBM/type/releases/tag/v0.5.0) using `local()` inside of the `@font-face()` tags.

It did not work for Light, SemiBold, and Italic weights. Chrome would ignore those weights and Safari would try to render a fake version. We are rolling back to v0.5.1 to only use `local()` on Regular weights until then.

@joshblack, do you have time to take a look at this?

**Comment by joshblack** [comment]
@seejamescode putting something for this in #96

**Comment by seejamescode** [comment]
Also tagging #88, which may of been why some of my local tags weren’t working.
