### ISSUE TITLE
Access

### ISSUE THREAD

**Issue by swiders2** [IBM/type#95]
Logged in with my IBM ID and get this:

_Access to this site is restricted. If you're an IBM agency partner who would like access, please email your name, agency and the purpose of your request to branding@us.ibm.com._

**Comment by seejamescode** [comment]
Hey @swiders2, IBM ID is a user account. That site requires an employee account.

**Comment by swiders2** [comment]
Correction, I logged in with my IBM employee account and received the error.

**Comment by seejamescode** [comment]
Thanks for the clarification, @swiders2. Please reach out to that team at branding@us.ibm.com.
