### ISSUE TITLE
Fonts are duplicated 4 times

### ISSUE THREAD

**Issue by jbicha** [IBM/type#97]
The same fonts are stored in `src/fonts/`, `fonts/`, `docs/fonts/`, and `guidelines/fonts/`

Maybe you could just point the references to the fonts to a single location?

Or maybe you could just use symlinks?

**Comment by seejamescode** [comment]
Thanks for the issue, @jbicha!

- `guidelines/fonts` will be deleted when add guidelines back to `docs`
- `docs/fonts` is necessary for gh-pages until we add the new docs in a separate `gh-pages` branch
- `fonts/` is necessary for discoverability by none-developers

You will see the changes mentioned above within the next couple of weeks!

**Comment by jbicha** [comment]
Hi, I'm unsatisfied with the answer you provided. Please at least consider using symlinks.

**Comment by seejamescode** [comment]
Are you able to use symlinks on github.com and GH-Pages?

**Comment by jbicha** [comment]
I don't use GitHub Pages, but it's worth a try. 🙂

**Comment by davelab6** [comment]
Yes, you can use symlinks in git repos.

You can also branch off master to a gh-pages branch, then set gh-pages as
default, and then remove master; then the docs folder won't be the only one
available on the web, and you can remove the fonts from there.

**Comment by moyogo** [comment]
> You can also branch off master to a gh-pages branch, then set gh-pages as default, and then remove master; then the docs folder won't be the only one available on the web, and you can remove the fonts from there.

Or simpler, you can set GitHub Pages to use master branch instead of master branch /docs folder.
